import "./globals.css";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";

import Link from "next/link";
import Image from "next/image";
import getPostMetadata from "../lib/getPostMetadata";
import PostPreview from "../components/PostPreview";
import dribbbleIcon from "../../public/icons8-dribbble.svg";
import githubIcon from "../../public/icons8-github.svg";
import linkedInIcon from "../../public/icons8-linkedin.svg";
import ScrollToTop from "../components/ScrollToTop";
import DSLogo from "../../public/Logo Icon.png";
import Nav from "../components/NavItem";
import NavItem from "@/components/NavItem";
import ExternalLink from "@/components/ExternalLink";
import Head from "next/head";

import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import mountains from "@/images/mountain.jpg";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const jetbrains_mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains_mono",
});

export const metadata: Metadata = {
  title: "Dylan Smith",
  description: "Generated by create next app",
};

// Photo by Joyston Judah: https://www.pexels.com/photo/white-and-black-mountain-wallpaper-933054/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const postMetadata = getPostMetadata();

  return (
    <html
      lang="en"
      className="scroll-smooth"
      suppressHydrationWarning
    >
      <Head>
        <link
          rel="stylesheet"
          href="https://rsms.me/inter/inter.css"
        />
      </Head>

      <body
        className={`${inter.variable} ${jetbrains_mono.variable} relative bg-slate-900 font-sans selection:bg-teal-300 selection:text-teal-900 h-screen overflow-hidden `}
      >
        <div className="flex flex-col mx-auto min-h-screen px-6 md:px-12 lg:px-24 overflow-hidden">
          <Image
            src={mountains}
            alt="mountains"
            placeholder="blur"
            quality={100}
            sizes="100vw"
            style={{ objectFit: "cover" }}
            fill
            className="-z-10"
          />

          {/* <div className="overflow-hidden"> */}
          {/* <div className="flex flex-col w-full h-screen"> */}
          <Header />

          <div className="flex flex-col mx-auto w-full overflow-hidden grow rounded-lg h-full">
            <main
              className={`${inter.variable} ${jetbrains_mono.variable} font-sans grow h-[100px] bg-gradient-to-b from-[#6c6573]/80 to-transparent text-[#031739] p-8 flex-auto overflow-y-auto w-full rounded-lg`}
            >
              {/* <main className="h-full bg-[#6c6573]/80 text-[#031739] p-4 flex-auto overflow-y-auto w-full rounded-lg"> */}
              {/* <div className="h-full grow bg-[#6c6573]/80 text-[#031739] p-4 flex-auto overflow-y-auto w-full rounded-lg"> */}
              <Providers>{children}</Providers>
              {/* </div> */}
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
